# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_templates/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.INIT_CONNECTOR_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.INIT_CONNECTOR_BTN.setGeometry(QtCore.QRect(570, 100, 161, 41))
        self.INIT_CONNECTOR_BTN.setObjectName("INIT_CONNECTOR_BTN")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(570, 150, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(550, 0, 222, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.SEND_HIST_REQUEST_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.SEND_HIST_REQUEST_BTN.setGeometry(QtCore.QRect(180, 340, 111, 51))
        self.SEND_HIST_REQUEST_BTN.setCheckable(False)
        self.SEND_HIST_REQUEST_BTN.setChecked(False)
        self.SEND_HIST_REQUEST_BTN.setObjectName("SEND_HIST_REQUEST_BTN")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 100, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(440, 290, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(380, 360, 256, 192))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.INIT_CONNECTOR_BTN.setText(_translate("MainWindow", "Init MT4 Connection"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.commandLinkButton.setText(_translate("MainWindow", "CommandLinkButton"))
        self.SEND_HIST_REQUEST_BTN.setText(_translate("MainWindow", "Request Hist Data"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
